export const SELECT_COURSE = "SELECT_COURSE";
export const UNSELECT_COURSE = "UNSELECT_COURSE";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
